### ISSUE TITLE
Precisa de ajuda para incluir no Get It Package Manager?

### ISSUE THREAD

**Issue by adrianosantostreina** [wakatime/delphi-wakatime#1]
Oi Diego, Adriano Santos aqui, talvez não me conheça.
Muito legal o projeto hein?

Cara, seria legal incluir seu projeto no Git It Package Manager, se precisar de ajuda, dá um toque. Me coloco à sua disposição pra ajudar. 

Parabéns.

**Comment by alanhamlett** [comment]
I've just submitted the request to add WakaTime to GitIt Package Manager.

**Comment by diegomgarcia** [comment]
Oi Adriano, obrigado. 

Acredito que nos conhecemos sim em um dos eventos da embarcadero, eu também já palestrei no passado. Inclusive antes da pandemia se não me falha a memória teve um evento da embarcadero onde teve um encontro de todos os MVPs e eu estava lá junto com o Cesar Romero. 

Valeu pela ajuda eu já tinha deixado aqui na minha lista para colocar no GetIt preenchendo o formulario da embarcadero mas já vi que o @alanhamlett já deu entrada no processo :)

Qualquer coisa te aviso.

Abraço!
----

Hi Adriano, thanks.

I believe we already meet in one of the embarcadero events, I have also spoken in the past. If I not mistaken before the pandemics we have an embarcadero event and there was an MVP meeting and I was with Cesar Romero.

Thanks for the help, I've already let scheduled to fill the request to add it to GetIt filling the necessary forms from embarcadero but I've just saw that @alanhamlett already done it :)

I will let you know if i need anything.

Regards. 

> Oi Diego, Adriano Santos aqui, talvez não me conheça. Muito legal o projeto hein?
> 
> Cara, seria legal incluir seu projeto no Git It Package Manager, se precisar de ajuda, dá um toque. Me coloco à sua disposição pra ajudar.
> 
> Parabéns.

**Comment by adrianosantostreina** [comment]
Sim, ele respondeu.
Top, vocês vão falar com o Serge Picko já, o cara que é responsável pelo
Get It.
Todos os MVPs gostaram e se puseram à disposição de ajudar vocês a colocar
no Get It.

Qualquer coisa que precisar, estou à disposição. Canal aberto.
Valeu, bas.

*Adriano Santos*
WhatsApp Comercial.: (11) 9-9831-0204



Em qui., 22 de jun. de 2023 às 14:34, Diego Garcia ***@***.***>
escreveu:

**Comment by diegomgarcia** [comment]
Valeu pela ajuda Adriano, vou te adicionar no whats e editar depois disso sua mensagem para não ficar exposto aqui no github. 

Abraços.


---

Thanks for the support Adriano, I will add you on whatsapp and edit your previous message removing the number to avoid been exposed here on github.

Regards.

**Comment by diegomgarcia** [comment]
Delphi Wakatime is now available on Get It Package Manager. 

Thanks Adriano, I will close this issue now ;)

**Comment by shaunroselt** [comment]
> Delphi Wakatime is now available on Get It Package Manager.
> 
> Thanks Adriano, I will close this issue now ;)

Installing via GetIt gives me an error every time. I'm using Delphi 11.3 Enterprise:
![Windows cannot find 'LL28Setup.exe'](https://github.com/wakatime/delphi-wakatime/assets/5418178/d5a8ddaa-1f77-4356-91d8-7692ef1faa20)


Installing directly from the source code works fine.
