### ISSUE TITLE
What is debug mode? No documetation about this

### ISSUE THREAD

**Issue by gorhinstroebel** [wakatime/delphi-wakatime#10]
Hi, I am setting up wakatime for the first time and there is an option to enable "debug mode" what is this for? There is no information in readme about this.

![image](https://github.com/wakatime/delphi-wakatime/assets/102311306/f41a4a35-39aa-417f-83a7-1b841d0fa7b5)

**Comment by alanhamlett** [comment]
It's the wakatime-cli debug setting to enable verbose logs in `~/.wakatime/wakatime.log`:

https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md#settings-section

**Comment by gorhinstroebel** [comment]
Thank you didnt see that doc

**Comment by shaunroselt** [comment]
Perhaps we should add a hint to the checkbox that would give a short description of what it does?
