### ISSUE TITLE
Adicionar suporte ao Delphi 10 Seattle

### ISSUE THREAD

**Issue by ramyres110** [wakatime/delphi-wakatime#15]
Adicionar suporte ao Delphi 10 Seattle

Criar pacote na versão Delphi 10 Seattle e disponibilizar.

Obs: Estou criado a issue para realizar o PR com a inclusão do pacote para o Delphi 10.

**Comment by diegomgarcia** [comment]
thanks for you collaboration @ramyres110! 

I've reviewed and merged.
